app:
  profile: prod

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://martinipooldb.cluster-coufnmierou8.ap-southeast-1.rds.amazonaws.com/martinipool?&zeroDateTimeBehavior=convertToNull&autoReconnect=true&noAccessToProcedureBodies=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    username: martinipool
    password: dpsdpvmxlfoqtm00!!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 26000
      maximum-pool-size: 20
    initialization-mode: always
    initialize: true
    sql-script-encoding: utf-8
    continue-on-error: true

# server
server:
  tomcat:
    basedir: /home/labshigh/logs/martinipool-scheduler

logging:
  file: /home/labshigh/logs/martinipool-scheduler/common.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
    rolling-file-name: /home/labshigh/logs/martinipool-scheduler/common.log.%d{yyyy-MM-dd}.%i.gz
  level:
    root: ERROR
    com:
      labshigh:
        martinipool: DEBUG

nftmoa:
  minting:
    api:
      url: http://52.78.220.163:3200

ethereum:
  url: https://mainnet.infura.io/v3/cdcb331cdcbc4dd4990d58fae3d72132
  token:

martinipool:
  wallet:
    api: http://10.0.0.141:9000

telegram:
  access_token: 6253167396:AAH8iFREQ9QcJkRTZCZPxHL-FbaadILqacI
  chat_id: -1001590574818